FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY src/ ./
RUN dotnet restore Relego.Server/Relego.Server.csproj
RUN dotnet publish Relego.Server/Relego.Server.csproj \
    --configuration Release \
    --output /out \
    --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

COPY --from=build /out/ ./

ENV ASPNETCORE_HTTP_PORTS=8080

RUN mkdir -p /data \
    && ln -s /data /app/.data

VOLUME ["/data"]
EXPOSE 8080

ENTRYPOINT ["dotnet", "Relego.Server.dll"]
