<Project>

  <PropertyGroup>
    <RelegoCoreVersion>0.8.0</RelegoCoreVersion>
    <RelegoCliVersion>0.15.5</RelegoCliVersion>
    <RelegoServerVersion>0.18.0</RelegoServerVersion>
    <PollyVersion>8.6.6</PollyVersion>
    <MicrosoftDataSqliteVersion>10.0.5</MicrosoftDataSqliteVersion>
  </PropertyGroup>

</Project>
